server:
  port: 8080
  error:
    include-message: always

management:
  server:
    port: 9080

logging:
  level:
    root: INFO

spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: DEFAULT
    active: DEFAULT,SECURE
    group:
      DEFAULT: SWAGGER,SBA,POSTGRES
      DEVLOCAL: SWAGGER,SBA,H2
      SECURE: SECURE_ERRORS,BCRYPT_ENCRYPTION
      INSECURE: INSECURE_ERRORS,MD5_ENCRYPTION
  jpa:
    show-sql: ${SHOW_SQL:false}
jwt:
  secret: ${JWT_SECRET}