SHOW_SQL: true

jwt:
  expire: 999999999

car-rental:
  users:
    starter:
      enabled: true
      data:
        admins:
          - password: 'Admin123321_#@!'
            email: 'admin_1@rental.com'
            first-name: 'Bob'
            last-name: 'Dylan'
            phone-number: '887102990'
            national-id: '92102005998'
            first-login-done: true
            enabled: true
            employee-identifier: 'ADM-1'
        employees:
          - password: 'Employee123321_#@!'
            email: 'employee_1@rental.com'
            first-name: 'Mike'
            last-name: 'Taylor'
            phone-number: '777102990'
            national-id: '82102005998'
            first-login-done: true
            enabled: true
            employee-identifier: 'EMP-1'
        clients:
          - password: 'Client123321_#@!'
            email: 'm.bohatko@gmail.com'
            first-name: 'Marcin'
            last-name: 'Bohatkiewicz'
            phone-number: '667102990'
            national-id: '86102005998'
            first-login-done: true
            enabled: true

  vehicles:
    starter:
      enabled: true
      data:
        vehicles:
          - plate: 'PLT1000'
            color: '1000'
            model: 'Tesla 10'
            state: new
            year-of-production: '2011'
            ensured-on-date: '2024-01-01'
            ensured-due-date: '2025-01-01'
            external-insurance-id: 1000

          - plate: 'PLT1001'
            color: '1000'
            model: 'Tesla 11'
            state: new
            year-of-production: '2012'
            ensured-on-date: '2024-01-01'
            ensured-due-date: '2025-01-01'
            external-insurance-id: 1001

          - plate: 'PLT1002'
            color: '1000'
            model: 'Tesla 12'
            state: in_repair
            year-of-production: '2012'
            ensured-on-date: '2024-01-01'
            ensured-due-date: '2025-01-01'
            external-insurance-id: 1002

          - plate: 'PLT1003'
            color: '1000'
            model: 'Tesla 13'
            state: just_returned
            year-of-production: '2013'
            ensured-on-date: '2024-01-01'
            ensured-due-date: '2025-01-01'
            external-insurance-id: 1003

          - plate: 'PLT1004'
            color: '1111'
            model: 'Tesla 14'
            state: ready_to_rent
            year-of-production: '2014'
            ensured-on-date: '2024-01-01'
            ensured-due-date: '2025-01-01'
            external-insurance-id: 1004

          - plate: 'PLT1005'
            color: '118A'
            model: 'Tesla 15'
            state: not_insured
            year-of-production: '2015'
