server:
  port: 8124
  error:
    include-message: always

management:
  server:
    port: 9080

logging:
  level:
    root: INFO

spring:
  thymeleaf:
    check-template-location: false
  config:
    import: optional:file:.env[.properties],optional:file:initial_users.yaml,optional:file:initial_vehicles.yaml
  profiles:
    default: DEFAULT
    active: DEFAULT,SECURE
    group:
      DEFAULT: SWAGGER,SBA,POSTGRES
      DEVLOCAL: SWAGGER,H2
      SECURE: SECURE_ERRORS,BCRYPT_ENCRYPTION #,SSL
      UNSECURE: UNSECURE_ERRORS,MD5_ENCRYPTION
      test: DEVLOCAL
  jpa:
    show-sql: ${SHOW_SQL:false}
  boot:
    admin:
      client:
        enabled: false
      server:
        enabled: false

jwt:
  secret: ${JWT_SECRET}

business:
  configuration:
    company:
      account-number: ${COMPANY_ACCOUNT_NUMBER}