SHOW_SQL: true
JWT_SECRET: absfol7814lqmva7891294nn9asa783nr293urnq9adm38ry2

jwt:
  expire: 999999999

car-rental:
  users:
    starter:
      enabled: true
      data:
        admins:
          - password: 'Admin123321_#@!'
            email: 'admin_1@rental.com'
            first-name: 'Bob'
            last-name: 'Dylan'
            phone-number: '887102990'
            national-id: '92102005998'
            first-login-done: true
            enabled: true
            employee-identifier: 'ADM-1'
        employees:
          - password: 'Employee123321_#@!'
            email: 'employee_1@rental.com'
            first-name: 'Mike'
            last-name: 'Taylor'
            phone-number: '777102990'
            national-id: '82102005998'
            first-login-done: true
            enabled: true
            employee-identifier: 'EMP-1'
        clients:
          - password: 'Client123321_#@!'
            email: 'm.bohatko@gmail.com'
            first-name: 'Marcin'
            last-name: 'Bohatkiewicz'
            phone-number: '667102990'
            national-id: '86102005998'
            first-login-done: true
            enabled: true

  vehicles:
    starter:
      enabled: true
      data:
        vehicles:
          - plate: 'PLT1000'
            color: '1000'
            model: 'Tesla 10'
            state: new
            year-of-production: '2011'
            ensured-on-date: '2024-01-01'
            ensured-due-date: '2025-01-01'
            external-insurance-id: 1000

          - plate: 'PLT1001'
            color: '1000'
            model: 'Tesla 11'
            state: new
            year-of-production: '2012'
            ensured-on-date: '2024-01-01'
            ensured-due-date: '2025-01-01'
            external-insurance-id: 1001

          - plate: 'PLT1002'
            color: '1000'
            model: 'Tesla 12'
            state: in_repair
            year-of-production: '2012'
            ensured-on-date: '2024-01-01'
            ensured-due-date: '2025-01-01'
            external-insurance-id: 1002

          - plate: 'PLT1003'
            color: '1000'
            model: 'Tesla 13'
            state: just_returned
            year-of-production: '2013'
            ensured-on-date: '2024-01-01'
            ensured-due-date: '2025-01-01'
            external-insurance-id: 1003

          - plate: 'PLT1004'
            color: '1111'
            model: 'Tesla 14'
            state: ready_to_rent
            rentPerDayPrice: 350.00
            year-of-production: '2014'
            ensured-on-date: '2024-01-01'
            ensured-due-date: '2025-01-01'
            external-insurance-id: 1004

          - plate: 'PLT1005'
            color: '118A'
            model: 'Tesla 15'
            state: not_insured
            year-of-production: '2015'

          - plate: 'PLT1006'
            color: '1111'
            model: '<img src="http://url.to.file.which/not.exist" onerror=alert(document.cookie);>'
            state: ready_to_rent
            rentPerDayPrice: 350.00
            year-of-production: '2015'
            ensured-on-date: '2024-01-01'
            ensured-due-date: '2025-01-01'
            external-insurance-id: 1006

          - plate: 'PLT1007'
            color: '1111'
            model: 'Tesla 15'
            state: rented
            rentPerDayPrice: 350.00
            year-of-production: '2015'
            ensured-on-date: '2024-01-01'
            ensured-due-date: '2026-01-01'
            external-insurance-id: 1007
            last-start-rent-date: '2025-01-01T00:00:00'

  rentals:
    starter:
      enabled: true
      data:
        rentals:

          - plate: 'PLT1007'
            client-email: 'm.bohatko@gmail.com'
            employee-email: 'employee_1@rental.com'
            rental-entity:
              state: active
              start-date: '2025-01-01T00:00:00'
              end-date: '2025-01-15T00:00:00'
              associated-payments:
                - status: pending
                  amount: 1500.00
                  due-date: '2025-01-15'
                  creation-date: '2025-01-01T00:00:00'
                  type: rental_fee